# Generated by Django 5.2.4 on 2025-08-13 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactfrom',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='contactfrom',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
