# Generated by Django 5.2.4 on 2025-08-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contactfrom_submitted_at_contactfrom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfrom',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
